Add internal mysql

diff --git a/assets/init b/assets/init
--- a/assets/init
+++ b/assets/init
@@ -17,13 +17,13 @@ SETUP_DIR="/app/setup"
 SYSCONF_TEMPLATES_DIR="${SETUP_DIR}/config"
 USERCONF_TEMPLATES_DIR="${DATA_DIR}/config"
 
-DB_HOST=${DB_HOST:-}
-DB_PORT=${DB_PORT:-}
-DB_NAME=${DB_NAME:-}
-DB_USER=${DB_USER:-}
+DB_HOST=${DB_HOST:-localhost}
+DB_PORT=${DB_PORT:-3306}
+DB_NAME=${DB_NAME:-redmine_production}
+DB_USER=${DB_USER:-root}
 DB_PASS=${DB_PASS:-}
 DB_POOL=${DB_POOL:-5}
-DB_TYPE=${DB_TYPE:-}
+DB_TYPE=${DB_TYPE:-mysql}
 
 MEMCACHED_HOST=${MEMCACHED_HOST:-}
 MEMCACHED_PORT=${MEMCACHED_PORT:-}
@@ -150,9 +150,42 @@ case "${DB_TYPE}" in
     ;;
 esac
 
-# set the default user and database
-DB_NAME=${DB_NAME:-redmine_production}
-DB_USER=${DB_USER:-root}
+# start mysql server if ${DB_HOST} is localhost
+if [ "${DB_HOST}" == "localhost" ]; then
+	if [ "${DB_TYPE}" == "postgres" ]; then
+		echo "DB_TYPE 'postgres' is not supported internally. Please provide DB_HOST."
+		exit 1
+	fi
+
+	# fix permissions and ownership of /var/lib/mysql
+	chown -R mysql:mysql /var/lib/mysql
+	chmod 700 /var/lib/mysql
+
+	# initialize MySQL data directory
+	if [ ! -d /var/lib/mysql/mysql ]; then
+		mysql_install_db --user=mysql
+	fi
+
+	echo "Starting mysql server..."
+	/usr/bin/mysqld_safe >/dev/null 2>&1 &
+
+	# wait for mysql server to start (max 120 seconds)
+	timeout=120
+	while ! mysqladmin -uroot ${DB_PASS:+-p$DB_PASS} status >/dev/null 2>&1
+	do
+		timeout=$(expr $timeout - 1)
+		if [ $timeout -eq 0 ]; then
+			echo "Failed to start mysql server"
+			exit 1
+		fi
+		sleep 1
+	done
+
+	if ! echo "USE ${DB_NAME}" | mysql -uroot ${DB_PASS:+-p$DB_PASS} >/dev/null 2>&1; then
+		echo "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` DEFAULT CHARACTER SET \`utf8\` COLLATE \`utf8_unicode_ci\`;" | mysql -uroot ${DB_PASS:+-p$DB_PASS}
+		echo "GRANT SELECT, LOCK TABLES, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON \`${DB_NAME}\`.* TO 'root'@'localhost';" | mysql -uroot ${DB_PASS:+-p$DB_PASS}
+	fi
+fi
 
 # is a memcached container linked?
 if [ -n "${MEMCACHED_PORT_11211_TCP_ADDR}" ]; then
